In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import RFECV, SelectKBest
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import classification_report

maindata = pd.read_csv("https://archive.ics.uci.edu/static/public/2/data.csv")
maindata.head()

maindata_processed = maindata.copy()

data_target = maindata["income"]

maindata_processed = maindata.drop(columns="income")

label_encoder = preprocessing.LabelEncoder()
data_target = label_encoder.fit_transform(data_target)

encoder = preprocessing.OneHotEncoder()
encoded = pd.DataFrame(encoder.fit_transform(maindata_processed[["workclass","education","marital-status","occupation","relationship","race","sex","native-country"]]).toarray(), columns=encoder.get_feature_names_out(["workclass","education","marital-status","occupation","relationship","race","sex","native-country"]))

maindata_processed = maindata_processed.drop(columns=["workclass","education","marital-status","occupation","relationship","race","sex","native-country"])
maindata_processed = maindata_processed.join(encoded)

data_train, data_test, target_train, target_test = train_test_split(
    maindata_processed, data_target,test_size=0.5, random_state=0, stratify=data_target)

display(data_test)
display(data_train)
# Assuming 'data' is your dataset with missing values, and 'target' is the target variable

# Load your dataset, replace this with your data loading process
# data = pd.read_csv('your_dataset.csv')

# Split your data into features and target variable
maindata_processed = maindata_processed.drop(columns=["workclass","education","marital-status","occupation","relationship","race","sex","native-country"])
  # Features
data_target = maindata["income"]  # Target variable

# Split the data into training and testing sets
data_train, data_test, target_train, target_test = train_test_split(
    maindata_processed, data_target,test_size=0.5, random_state=42)


# Impute missing values - replace NaN values with mean of each column
imputer = SimpleImputer(strategy='mean')
data_train_imputed = imputer.fit_transform(data_train)
data_test_imputed = imputer.transform(data_test)

# Initialize Naive Bayes Classifier
nb_classifier = GaussianNB()

# Train the classifier on the imputed data
nb_classifier.fit(data_train_imputed, target_train)

# Predict on the test set
target_pred = nb_classifier.predict(data_test_imputed)

# Calculate accuracy
accuracy = accuracy_score(target_test, target_pred)
print(f"Accuracy: {accuracy}")

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,workclass_?,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,native-country_nan
40770,46,36020,13,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
44393,52,289804,13,0,0,40,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
40429,41,274158,10,0,0,30,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
44255,45,111706,2,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4961,28,51331,12,0,0,16,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47300,44,185832,9,7298,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
44119,26,181613,9,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
31559,33,133503,9,7688,0,48,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1854,29,229842,9,0,0,45,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48162,48,83545,10,0,0,65,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,workclass_?,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,native-country_nan
42920,55,228595,3,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
34381,32,100154,5,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48283,40,229148,9,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15587,48,204990,9,0,0,33,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47592,47,210557,9,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,51,133461,10,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10580,48,148995,13,0,0,60,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4202,59,193895,9,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15806,45,84324,12,0,0,50,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14908,19,86150,7,0,0,19,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

KeyError: "['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country'] not found in axis"